apiVersion: v1
kind: Service
metadata:
  name: {{ template "notary.fullname" . }}
  labels:
    app: {{ template "notary.name" . }}
    chart: {{ template "notary.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: nuts
  selector:
    app: {{ template "notary.name" . }}
    release: {{ .Release.Name }}
